-- AutoCount Creditor master used as the read-only supplier source for MAW Purchase Orders.

CREATE TABLE IF NOT EXISTS `Creditor` (
  `AccNo` VARCHAR(100) NOT NULL,
  `CompanyName` VARCHAR(255) NULL,
  `Desc2` TEXT NULL,
  `RegisterNo` VARCHAR(100) NULL,
  `Address1` TEXT NULL,
  `Address2` TEXT NULL,
  `Address3` TEXT NULL,
  `Address4` TEXT NULL,
  `PostCode` VARCHAR(50) NULL,
  `Attention` VARCHAR(100) NULL,
  `Phone1` VARCHAR(50) NULL,
  `Phone2` VARCHAR(50) NULL,
  `Fax1` VARCHAR(50) NULL,
  `Fax2` VARCHAR(50) NULL,
  `AreaCode` VARCHAR(50) NULL,
  `PurchaseAgent` VARCHAR(50) NULL,
  `CreditorType` VARCHAR(50) NULL,
  `NatureOfBusiness` VARCHAR(100) NULL,
  `WebURL` VARCHAR(255) NULL,
  `EmailAddress` VARCHAR(255) NULL,
  `DisplayTerm` VARCHAR(50) NULL,
  `CreditLimit` DECIMAL(18,4) NULL,
  `AgingOn` VARCHAR(50) NULL,
  `CurrencyCode` VARCHAR(50) NULL,
  `AllowExceedCreditLimit` CHAR(1) NULL,
  `Note` TEXT NULL,
  `TaxCode` VARCHAR(50) NULL,
  `DiscountPercent` DECIMAL(18,4) NULL,
  `LastModified` DATETIME NULL,
  `LastModifiedUserID` VARCHAR(50) NULL,
  `CreatedTimeStamp` DATETIME NULL,
  `CreatedUserID` VARCHAR(50) NULL,
  `IsActive` CHAR(1) NULL,
  `LastUpdate` DATETIME NULL,
  `ContactInfo` TEXT NULL,
  `AccountGroup` VARCHAR(50) NULL,
  `InclusiveTax` CHAR(1) NULL,
  `RoundingMethod` VARCHAR(50) NULL,
  `IsTaxRegistered` CHAR(1) NULL,
  `WithholdingTaxCode` VARCHAR(50) NULL,
  `SelfBilledApprovalNo` VARCHAR(100) NULL,
  `AutoKey` INT NULL,
  `Guid` VARCHAR(100) NULL,
  `Mobile` VARCHAR(50) NULL,
  `TaxEntityID` VARCHAR(50) NULL,
  `DoNotSubmitEInvoice` CHAR(1) NULL,
  PRIMARY KEY (`AccNo`),
  KEY `idx_creditor_company_name` (`CompanyName`),
  KEY `idx_creditor_active` (`IsActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'AutoCount Creditor master is ready.' AS migration_result;
